name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Jellyfin.Plugin.MoviesRefine/Jellyfin.Plugin.MoviesRefine.csproj

    - name: Build
      run: dotnet build Jellyfin.Plugin.MoviesRefine/Jellyfin.Plugin.MoviesRefine.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet run --project PluginTester.cs
    
    - name: Extract version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create plugin package
      run: |
        mkdir -p plugin-package
        cp Jellyfin.Plugin.MoviesRefine/bin/Release/net6.0/Jellyfin.Plugin.MoviesRefine.dll plugin-package/
        cd plugin-package
        zip -r ../jellyfin-movies-refine_${{ steps.get_version.outputs.VERSION || '1.0.0.0' }}.zip .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugin-zip
        path: jellyfin-movies-refine_${{ steps.get_version.outputs.VERSION || '1.0.0.0' }}.zip
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: jellyfin-movies-refine_${{ steps.get_version.outputs.VERSION }}.zip